name: Deploy To Netlify
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  playwright-tests:
    uses: ./.github/workflows/playwright.yml

  deploy:
    needs: [unit-tests, playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: cd client && npm ci && npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=client/build --site=$NETLIFY_SITE_ID
